import re, sys
raw = open(sys.argv[1]).read()
raw = re.sub(r"/\*.*?\*/", "", raw, flags=re.S)

def arr(name):
    body = raw.split(name, 1)[1].split("{", 1)[1]
    depth, out, i = 1, [], 0
    while depth:
        c = body[i]
        if c == "{": depth += 1
        elif c == "}": depth -= 1
        out.append(c); i += 1
    return "".join(out[:-1])

prmnofsf = [int(x) for x in re.findall(r"-?\d+", arr("prmnofsf[NUM_OF_SPMODES]"))]
# The reference declares one array per mode and then an array of pointers.
names = ["dfh_M7k", "dfh_M9k", "dfh_M12k", "dfh_M14k", "dfh_M16k",
         "dfh_M18k", "dfh_M20k", "dfh_M23k", "dfh_M24k"]
rows = []
for n in names:
    body = arr(n + "[")
    rows.append([int(x, 0) for x in re.findall(r"-?0[xX][0-9a-fA-F]+|-?\d+", body)])
assert len(rows) == 9, len(rows)
assert len(prmnofsf) == 9, prmnofsf

def i16(v):
    return v - 0x10000 if v > 0x7FFF else v

print('//! Homing-frame patterns for AMR-WB, from the TS 26.173 reference.')
print('//!')
print('//! A homing frame is the specification\'s own way of driving a codec to a')
print('//! known state mid-stream: feed the encoder a frame of `0x0008` samples and')
print('//! it emits exactly the pattern below, then resets. The decoder does the')
print('//! mirror. Conformance sequences open with them, which is why the wideband')
print('//! encoder vectors cannot be reproduced without this.')
print('//!')
print('//! Generated by `tools/gen_homing_tables.py`.')
print()
print('/// Parameters in the first subframe of each mode, for the partial test.')
print('///')
print('/// A decoder already in its homed state checks only these: the rest of the')
print('/// frame carries the *next* frame\'s content once homing has taken effect.')
print(f'pub const PRMS_FIRST_SUBFRAME: [usize; 9] = {prmnofsf};')
print()
print('/// The parameter pattern each mode\'s decoder homing frame carries.')
print('///')
print('/// Rows are padded to the longest mode; only the leading `PRMS_*` entries of')
print('/// each are meaningful.')
print('pub const DHF: [[i16; 32]; 9] = [')
for r in rows:
    padded = r + [0] * (32 - len(r))
    print("    [" + ", ".join(str(i16(v)) for v in padded) + "],")
print('];')
