#!/usr/bin/env python3
"""Emit the AMR-NB bit-ordering and parameter-layout tables as Rust.

From TS 26.073's bitno.tab, which carries both:

- `sort_*`, mapping payload bit position to codec bit position, exactly as
  AMR-WB's mime_io.tab does;
- `bitno_MR*`, the width of each parameter in the order the decoder reads them.

The second is what makes AMR-NB's layout tractable. AMR-WB has one parameter
layout with a few mode-dependent field widths; AMR-NB has eight genuinely
different layouts, and the reference expresses each as a flat list of widths
rather than as code.
"""
import re
import sys

tab_path, out_path = sys.argv[1], sys.argv[2]
raw = open(tab_path).read()

# (C name, Rust name, length, human label)
SORT_TABLES = [
    ("sort_475", "SORT_475", 95, "4.75 kbit/s"),
    ("sort_515", "SORT_515", 103, "5.15 kbit/s"),
    ("sort_59", "SORT_59", 118, "5.90 kbit/s"),
    ("sort_67", "SORT_67", 134, "6.70 kbit/s"),
    ("sort_74", "SORT_74", 148, "7.40 kbit/s"),
    ("sort_795", "SORT_795", 159, "7.95 kbit/s"),
    ("sort_102", "SORT_102", 204, "10.2 kbit/s"),
    ("sort_122", "SORT_122", 244, "12.2 kbit/s"),
    ("sort_SID", "SORT_SID", 35, "SID (comfort noise)"),
]

BITNO_TABLES = [
    ("bitno_MR475", "BITNO_475", "4.75 kbit/s"),
    ("bitno_MR515", "BITNO_515", "5.15 kbit/s"),
    ("bitno_MR59", "BITNO_59", "5.90 kbit/s"),
    ("bitno_MR67", "BITNO_67", "6.70 kbit/s"),
    ("bitno_MR74", "BITNO_74", "7.40 kbit/s"),
    ("bitno_MR795", "BITNO_795", "7.95 kbit/s"),
    ("bitno_MR102", "BITNO_102", "10.2 kbit/s"),
    ("bitno_MR122", "BITNO_122", "12.2 kbit/s"),
    ("bitno_MRDTX", "BITNO_SID", "SID (comfort noise)"),
]


def values(name):
    body = raw.split(f"{name}[", 1)[1].split("{", 1)[1].split("}", 1)[0]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    return [int(x) for x in re.findall(r"-?\d+", body)]


parts = []

for c_name, rust_name, count, label in SORT_TABLES:
    vals = values(c_name)
    assert len(vals) == count, f"{c_name}: got {len(vals)}, want {count}"
    # A sorting table is a permutation; anything else is a transcription error.
    assert sorted(vals) == list(range(count)), f"{c_name} is not a permutation"
    lines = [
        f"/// Payload bit order for the {label} mode, {count} bits.",
        f"pub const {rust_name}: [u16; {count}] = [",
    ]
    for i in range(0, count, 10):
        lines.append("    " + ", ".join(str(v) for v in vals[i : i + 10]) + ",")
    lines.append("];")
    parts.append("\n".join(lines))

for c_name, rust_name, label in BITNO_TABLES:
    vals = values(c_name)
    total = sum(vals)
    lines = [
        f"/// Parameter widths for the {label} mode, in decoder read order.",
        "///",
        f"/// {len(vals)} parameters, {total} bits.",
        f"pub const {rust_name}: [usize; {len(vals)}] = [",
    ]
    for i in range(0, len(vals), 12):
        lines.append("    " + ", ".join(str(v) for v in vals[i : i + 12]) + ",")
    lines.append("];")
    parts.append("\n".join(lines))

# Cross-check the two families agree on frame length. They are independent
# tables in the reference, so a disagreement means one was transcribed wrong.
for (sc, _, count, label), (bc, _, _) in zip(SORT_TABLES, BITNO_TABLES):
    assert sum(values(bc)) == count, (
        f"{label}: bitno sums to {sum(values(bc))} but {sc} has {count} entries"
    )

HEADER = '''//! Bit-ordering and parameter-layout tables for AMR-NB, from TS 26.073.
//!
//! Two families, both from `bitno.tab`:
//!
//! - `SORT_*` maps payload bit position to codec bit position, exactly as
//!   AMR-WB's tables do. RFC 4867 carries the bits sorted by subjective
//!   importance rather than in decoder order.
//! - `BITNO_*` gives each parameter's width in the order the decoder reads
//!   them. This is what makes eight genuinely different frame layouts
//!   tractable: the reference expresses each as a flat list rather than as
//!   code, and so does this.
//!
//! Generated by `tools/gen_nb_tables.py`, which checks each sorting table is a
//! true permutation and that the two families agree on every frame length --
//! they are independent tables in the reference, so a disagreement means one
//! was transcribed wrong.

'''

with open(out_path, "w") as f:
    f.write(HEADER)
    f.write("\n\n".join(parts) + "\n")

print(f"wrote {out_path}: {len(SORT_TABLES)} sorting + {len(BITNO_TABLES)} layout tables")
