#!/usr/bin/env python3
"""Emit the AMR-WB comfort-noise ISF quantiser tables as Rust from TS 26.173."""
import re
import sys

tab_path, out_path = sys.argv[1], sys.argv[2]
raw = open(tab_path).read()

# (C name, Rust name, entries, vector dimension)
BOOKS = [
    ("mean_isf_noise", "MEAN_ISF_NOISE", 16, 1),
    ("dico1_isf_noise", "DICO1_NS", 64, 2),
    ("dico2_isf_noise", "DICO2_NS", 64, 3),
    ("dico3_isf_noise", "DICO3_NS", 64, 3),
    ("dico4_isf_noise", "DICO4_NS", 32, 4),
    ("dico5_isf_noise", "DICO5_NS", 32, 4),
]

DOCS = {
    "MEAN_ISF_NOISE": (
        "Long-term mean ISF vector for comfort noise, Q15.\n"
        "///\n"
        "/// Subtracted before quantisation and added back after. Distinct from the\n"
        "/// speech quantiser's `MEAN_ISF`: a noise spectrum is not a speech spectrum,\n"
        "/// and the two means differ in every coefficient."
    ),
    "DICO1_NS": "Comfort-noise codebook, ISFs 0-1, 64 entries of 2. 6 bits.",
    "DICO2_NS": "Comfort-noise codebook, ISFs 2-4, 64 entries of 3. 6 bits.",
    "DICO3_NS": "Comfort-noise codebook, ISFs 5-7, 64 entries of 3. 6 bits.",
    "DICO4_NS": "Comfort-noise codebook, ISFs 8-11, 32 entries of 4. 5 bits.",
    "DICO5_NS": "Comfort-noise codebook, ISFs 12-15, 32 entries of 4. 5 bits.",
}


def values(name, count):
    """Numbers inside one C array initialiser."""
    body = raw.split(f"{name}[", 1)[1].split("{", 1)[1].split("}", 1)[0]
    # Strip comments before scanning, so numbers inside them are not picked up.
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    vals = [int(x) for x in re.findall(r"-?\d+", body)]
    assert len(vals) == count, f"{name}: got {len(vals)}, want {count}"
    return vals


def table(rust_name, vals, dim, per_line=8):
    doc = DOCS[rust_name]
    lines = [f"/// {doc}", f"pub const {rust_name}: [i16; {len(vals)}] = ["]
    step = dim if 1 < dim <= per_line else per_line
    for i in range(0, len(vals), step):
        lines.append("    " + ", ".join(str(v) for v in vals[i : i + step]) + ",")
    lines.append("];")
    return "\n".join(lines)


HEADER = '''//! Comfort-noise ISF quantiser tables for AMR-WB, from the TS 26.173 reference.
//!
//! A SID frame carries 35 bits, 28 of which are the spectrum. That buys a
//! five-way split of the sixteen ISFs at 6/6/6/5/5 bits -- against the speech
//! quantiser's 46 -- and no prediction at all: the noise quantiser is
//! memoryless, where the speech one carries a moving-average predictor across
//! frames. Comfort noise has to survive being decoded after an arbitrary gap,
//! so there is nothing to predict from.
//!
//! These are normative constants -- the codec cannot be conformant without
//! exactly these numbers -- and are generated by `tools/gen_isf_noise_tables.py`.

'''

with open(out_path, "w") as f:
    f.write(HEADER)
    parts = []
    for c_name, rust_name, count, dim in BOOKS:
        parts.append(table(rust_name, values(c_name, count * dim), dim))
    f.write("\n\n".join(parts) + "\n")

# The two mean vectors must differ, or one of them was read from the wrong
# table -- they are the same length and the same Q format, so a mix-up compiles
# and produces a plausible spectrum.
speech_tab = tab_path.replace("qisf_ns.tab", "qpisf_2s.tab")
try:
    speech_raw = open(speech_tab).read()
    body = speech_raw.split("mean_isf[", 1)[1].split("{", 1)[1].split("}", 1)[0]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    speech_mean = [int(x) for x in re.findall(r"-?\d+", body)]
    noise_mean = values("mean_isf_noise", 16)
    assert speech_mean != noise_mean, "the speech and noise ISF means are identical"
    shared = sum(1 for a, b in zip(speech_mean, noise_mean) if a == b)
    assert shared == 0, f"{shared} coefficients shared between the two means"
except FileNotFoundError:
    print(f"note: {speech_tab} absent, skipped the mean-vector distinctness check")

print(f"wrote {out_path}: {len(BOOKS)} tables")
