//! Deterministic SRTP/SRTCP driver used by `scripts/test_libsrtp_interop.sh`.
//!
//! The RTP vector comes from libSRTP's `srtp_validate` test. SRTCP uses a
//! structurally valid Sender Report and wire answers generated by the exact
//! commit pinned by that script. Keeping this driver dependency-free makes the
//! gate usable without adding libSRTP to the Rust dependency graph.

use rvoip_rtp_core::packet::RtpPacket;
use rvoip_rtp_core::srtp::{
    SrtpContext, SrtpCryptoKey, SrtpCryptoSuite, SRTP_AES128_CM_SHA1_32, SRTP_AES128_CM_SHA1_80,
    SRTP_AES256_CM_SHA1_32, SRTP_AES256_CM_SHA1_80,
};
use std::error::Error;

const MASTER_KEY: [u8; 16] = [
    0xe1, 0xf9, 0x7a, 0x0d, 0x3e, 0x01, 0x8b, 0xe0, 0xd6, 0x4f, 0xa3, 0x2c, 0x06, 0xde, 0x41, 0x39,
];
const MASTER_SALT: [u8; 14] = [
    0x0e, 0xc6, 0x75, 0xad, 0x49, 0x8a, 0xfe, 0xeb, 0xb6, 0x96, 0x0b, 0x3a, 0xab, 0xe6,
];
const MASTER_KEY_256: [u8; 32] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
];

const RTP_PLAINTEXT: [u8; 28] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0xab, 0xab, 0xab, 0xab,
    0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab,
];
const SRTP_CIPHERTEXT: [u8; 38] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0x4e, 0x55, 0xdc, 0x4c,
    0xe7, 0x99, 0x78, 0xd8, 0x8c, 0xa4, 0xd2, 0x15, 0x94, 0x9d, 0x24, 0x02, 0xb7, 0x8d, 0x6a, 0xcc,
    0x99, 0xea, 0x17, 0x9b, 0x8d, 0xbb,
];
const SRTP_SHA1_32_CIPHERTEXT: [u8; 32] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0x4e, 0x55, 0xdc, 0x4c,
    0xe7, 0x99, 0x78, 0xd8, 0x8c, 0xa4, 0xd2, 0x15, 0x94, 0x9d, 0x24, 0x02, 0xb7, 0x8d, 0x6a, 0xcc,
];
const SRTP_AES256_SHA1_80_CIPHERTEXT: [u8; 38] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0x2e, 0xaf, 0xab, 0x4c,
    0x54, 0x11, 0xba, 0xca, 0x23, 0x55, 0xd5, 0x53, 0xeb, 0x99, 0xf2, 0x52, 0x0e, 0x6b, 0x00, 0xdb,
    0xd5, 0x1d, 0x0c, 0x94, 0xfc, 0x25,
];
const SRTP_AES256_SHA1_32_CIPHERTEXT: [u8; 32] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0x2e, 0xaf, 0xab, 0x4c,
    0x54, 0x11, 0xba, 0xca, 0x23, 0x55, 0xd5, 0x53, 0xeb, 0x99, 0xf2, 0x52, 0x0e, 0x6b, 0x00, 0xdb,
];

const RTCP_PLAINTEXT: [u8; 28] = [
    0x80, 0xc8, 0x00, 0x06, 0xca, 0xfe, 0xba, 0xbe, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab,
    0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab,
];
const SRTCP_CIPHERTEXT: [u8; 42] = [
    0x80, 0xc8, 0x00, 0x06, 0xca, 0xfe, 0xba, 0xbe, 0x71, 0x28, 0x03, 0x5b, 0xe4, 0x87, 0xb9, 0xbd,
    0xbe, 0xf8, 0x90, 0x41, 0xf9, 0x77, 0xa5, 0xa8, 0xd5, 0xef, 0xb8, 0x81, 0x80, 0x00, 0x00, 0x01,
    0x90, 0x5c, 0x6f, 0x4d, 0x79, 0x32, 0xc1, 0xca, 0xa1, 0x82,
];
const SRTCP_AES256_CIPHERTEXT: [u8; 42] = [
    0x80, 0xc8, 0x00, 0x06, 0xca, 0xfe, 0xba, 0xbe, 0x90, 0x22, 0x6f, 0x76, 0x90, 0x76, 0x83, 0x87,
    0x99, 0xdb, 0x59, 0xe0, 0x76, 0x80, 0x16, 0x3b, 0xc3, 0x03, 0x8c, 0x6e, 0x80, 0x00, 0x00, 0x01,
    0x02, 0x5f, 0xed, 0xdf, 0x1a, 0xd3, 0x45, 0x0e, 0x4d, 0x12,
];
const ROLLOVER_SEQUENCES: [u16; 2] = [u16::MAX, 0];

fn suite(profile: &str) -> Result<SrtpCryptoSuite, String> {
    match profile {
        "sha1-80" => Ok(SRTP_AES128_CM_SHA1_80),
        "sha1-32" => Ok(SRTP_AES128_CM_SHA1_32),
        "aes256-sha1-80" => Ok(SRTP_AES256_CM_SHA1_80),
        "aes256-sha1-32" => Ok(SRTP_AES256_CM_SHA1_32),
        _ => Err(format!("unsupported SRTP profile `{profile}`")),
    }
}

fn expected_srtp(profile: &str) -> Result<&'static [u8], String> {
    match profile {
        "sha1-80" => Ok(&SRTP_CIPHERTEXT),
        "sha1-32" => Ok(&SRTP_SHA1_32_CIPHERTEXT),
        "aes256-sha1-80" => Ok(&SRTP_AES256_SHA1_80_CIPHERTEXT),
        "aes256-sha1-32" => Ok(&SRTP_AES256_SHA1_32_CIPHERTEXT),
        _ => Err(format!("unsupported SRTP profile `{profile}`")),
    }
}

fn context(profile: &str) -> Result<SrtpContext, Box<dyn Error>> {
    let key = if profile.starts_with("aes256-") {
        MASTER_KEY_256.to_vec()
    } else {
        MASTER_KEY.to_vec()
    };
    SrtpContext::new(
        suite(profile)?,
        SrtpCryptoKey::new(key, MASTER_SALT.to_vec()),
    )
    .map_err(Into::into)
}

fn encode_hex(bytes: &[u8]) -> String {
    let mut result = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        use std::fmt::Write as _;
        write!(&mut result, "{byte:02x}").expect("writing to String cannot fail");
    }
    result
}

fn decode_hex(value: &str) -> Result<Vec<u8>, String> {
    if value.len() % 2 != 0 {
        return Err("hex input must contain an even number of characters".to_string());
    }

    value
        .as_bytes()
        .chunks_exact(2)
        .enumerate()
        .map(|(index, pair)| {
            let digits = std::str::from_utf8(pair)
                .map_err(|_| format!("invalid UTF-8 at hex byte {index}"))?;
            u8::from_str_radix(digits, 16)
                .map_err(|_| format!("invalid hex byte `{digits}` at offset {}", index * 2))
        })
        .collect()
}

fn rtp_plaintext_with_sequence(sequence: u16) -> [u8; RTP_PLAINTEXT.len()] {
    let mut packet = RTP_PLAINTEXT;
    packet[2..4].copy_from_slice(&sequence.to_be_bytes());
    packet
}

fn require_expected(label: &str, actual: &[u8], expected: &[u8]) -> Result<(), String> {
    if actual == expected {
        return Ok(());
    }

    Err(format!(
        "{label} did not match libSRTP v2.8.0 known answer\nexpected: {}\nactual:   {}",
        encode_hex(expected),
        encode_hex(actual)
    ))
}

fn protect_rtp(profile: &str) -> Result<(), Box<dyn Error>> {
    let packet = RtpPacket::parse(&RTP_PLAINTEXT)?;
    let wire = context(profile)?.protect(&packet)?.serialize()?;
    require_expected("SRTP ciphertext", &wire, expected_srtp(profile)?)?;
    println!("{}", encode_hex(&wire));
    Ok(())
}

fn unprotect_rtp(profile: &str, input: &str) -> Result<(), Box<dyn Error>> {
    let wire = decode_hex(input)?;
    let plaintext = context(profile)?.unprotect(&wire)?.serialize()?;
    require_expected("RTP plaintext", &plaintext, &RTP_PLAINTEXT)?;
    println!("ok");
    Ok(())
}

fn protect_rtcp(profile: &str) -> Result<(), Box<dyn Error>> {
    let wire = context(profile)?.protect_rtcp(&RTCP_PLAINTEXT)?;
    let expected = if profile.starts_with("aes256-") {
        &SRTCP_AES256_CIPHERTEXT[..]
    } else {
        &SRTCP_CIPHERTEXT[..]
    };
    require_expected("SRTCP ciphertext", &wire, expected)?;
    println!("{}", encode_hex(&wire));
    Ok(())
}

fn unprotect_rtcp(profile: &str, input: &str) -> Result<(), Box<dyn Error>> {
    let wire = decode_hex(input)?;
    let plaintext = context(profile)?.unprotect_rtcp(&wire)?;
    require_expected("RTCP plaintext", &plaintext, &RTCP_PLAINTEXT)?;
    println!("ok");
    Ok(())
}

fn protect_rtp_rollover(profile: &str) -> Result<(), Box<dyn Error>> {
    let mut context = context(profile)?;
    let mut protected = Vec::with_capacity(ROLLOVER_SEQUENCES.len());
    for sequence in ROLLOVER_SEQUENCES {
        let plaintext = rtp_plaintext_with_sequence(sequence);
        let packet = RtpPacket::parse(&plaintext)?;
        let wire = context.protect(&packet)?.serialize()?;
        protected.push(encode_hex(&wire));
    }
    println!("{}", protected.join(":"));
    Ok(())
}

fn unprotect_rtp_rollover(profile: &str, input: &str) -> Result<(), Box<dyn Error>> {
    let packets: Vec<&str> = input.split(':').collect();
    if packets.len() != ROLLOVER_SEQUENCES.len() {
        return Err(format!(
            "rollover input must contain {} packets, got {}",
            ROLLOVER_SEQUENCES.len(),
            packets.len()
        )
        .into());
    }

    let mut context = context(profile)?;
    for (encoded, sequence) in packets.into_iter().zip(ROLLOVER_SEQUENCES) {
        let wire = decode_hex(encoded)?;
        let plaintext = context.unprotect(&wire)?.serialize()?;
        require_expected(
            "rollover RTP plaintext",
            &plaintext,
            &rtp_plaintext_with_sequence(sequence),
        )?;
    }
    println!("ok");
    Ok(())
}

fn usage() -> &'static str {
    "usage: libsrtp_interop_driver <sha1-80|sha1-32|aes256-sha1-80|aes256-sha1-32> <protect-rtp|unprotect-rtp|protect-rtcp|unprotect-rtcp|protect-rtp-rollover|unprotect-rtp-rollover> [hex-packet]"
}

fn main() -> Result<(), Box<dyn Error>> {
    let mut args = std::env::args().skip(1);
    match (
        args.next(),
        args.next().as_deref(),
        args.next(),
        args.next(),
    ) {
        (Some(profile), Some("protect-rtp"), None, None) => protect_rtp(&profile),
        (Some(profile), Some("unprotect-rtp"), Some(input), None) => {
            unprotect_rtp(&profile, &input)
        }
        (Some(profile), Some("protect-rtcp"), None, None) => protect_rtcp(&profile),
        (Some(profile), Some("unprotect-rtcp"), Some(input), None) => {
            unprotect_rtcp(&profile, &input)
        }
        (Some(profile), Some("protect-rtp-rollover"), None, None) => protect_rtp_rollover(&profile),
        (Some(profile), Some("unprotect-rtp-rollover"), Some(input), None) => {
            unprotect_rtp_rollover(&profile, &input)
        }
        _ => Err(usage().into()),
    }
}
