//! Known-answer coverage against pinned libSRTP.
//!
//! The RTP input is libSRTP's `srtp_validate` vector. The SRTCP input is a
//! structurally valid 28-byte Sender Report (the upstream crypto-only fixture
//! declares 48 bytes while providing only 24). Expected wire bytes were
//! generated by Cisco libSRTP v2.8.0 at commit
//! `24b3bf8f19b6f5ab4cd2bcceb4f4064efca86fd5` and are also checked by the
//! bidirectional external gate.

use rvoip_rtp_core::packet::RtpPacket;
use rvoip_rtp_core::srtp::{
    SrtpContext, SrtpCryptoKey, SrtpCryptoSuite, SRTP_AES128_CM_SHA1_32, SRTP_AES128_CM_SHA1_80,
    SRTP_AES256_CM_SHA1_32, SRTP_AES256_CM_SHA1_80,
};

const MASTER_KEY: [u8; 16] = [
    0xe1, 0xf9, 0x7a, 0x0d, 0x3e, 0x01, 0x8b, 0xe0, 0xd6, 0x4f, 0xa3, 0x2c, 0x06, 0xde, 0x41, 0x39,
];
const MASTER_SALT: [u8; 14] = [
    0x0e, 0xc6, 0x75, 0xad, 0x49, 0x8a, 0xfe, 0xeb, 0xb6, 0x96, 0x0b, 0x3a, 0xab, 0xe6,
];
const MASTER_KEY_256: [u8; 32] = [
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f,
];
const RTP_PLAINTEXT: [u8; 28] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0xab, 0xab, 0xab, 0xab,
    0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab,
];
const SRTP_CIPHERTEXT: [u8; 38] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0x4e, 0x55, 0xdc, 0x4c,
    0xe7, 0x99, 0x78, 0xd8, 0x8c, 0xa4, 0xd2, 0x15, 0x94, 0x9d, 0x24, 0x02, 0xb7, 0x8d, 0x6a, 0xcc,
    0x99, 0xea, 0x17, 0x9b, 0x8d, 0xbb,
];
const SRTP_SHA1_32_CIPHERTEXT: [u8; 32] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0x4e, 0x55, 0xdc, 0x4c,
    0xe7, 0x99, 0x78, 0xd8, 0x8c, 0xa4, 0xd2, 0x15, 0x94, 0x9d, 0x24, 0x02, 0xb7, 0x8d, 0x6a, 0xcc,
];
const SRTP_AES256_SHA1_80_CIPHERTEXT: [u8; 38] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0x2e, 0xaf, 0xab, 0x4c,
    0x54, 0x11, 0xba, 0xca, 0x23, 0x55, 0xd5, 0x53, 0xeb, 0x99, 0xf2, 0x52, 0x0e, 0x6b, 0x00, 0xdb,
    0xd5, 0x1d, 0x0c, 0x94, 0xfc, 0x25,
];
const SRTP_AES256_SHA1_32_CIPHERTEXT: [u8; 32] = [
    0x80, 0x0f, 0x12, 0x34, 0xde, 0xca, 0xfb, 0xad, 0xca, 0xfe, 0xba, 0xbe, 0x2e, 0xaf, 0xab, 0x4c,
    0x54, 0x11, 0xba, 0xca, 0x23, 0x55, 0xd5, 0x53, 0xeb, 0x99, 0xf2, 0x52, 0x0e, 0x6b, 0x00, 0xdb,
];
const RTCP_PLAINTEXT: [u8; 28] = [
    0x80, 0xc8, 0x00, 0x06, 0xca, 0xfe, 0xba, 0xbe, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab,
    0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab,
];
const SRTCP_CIPHERTEXT: [u8; 42] = [
    0x80, 0xc8, 0x00, 0x06, 0xca, 0xfe, 0xba, 0xbe, 0x71, 0x28, 0x03, 0x5b, 0xe4, 0x87, 0xb9, 0xbd,
    0xbe, 0xf8, 0x90, 0x41, 0xf9, 0x77, 0xa5, 0xa8, 0xd5, 0xef, 0xb8, 0x81, 0x80, 0x00, 0x00, 0x01,
    0x90, 0x5c, 0x6f, 0x4d, 0x79, 0x32, 0xc1, 0xca, 0xa1, 0x82,
];
const SRTCP_AES256_CIPHERTEXT: [u8; 42] = [
    0x80, 0xc8, 0x00, 0x06, 0xca, 0xfe, 0xba, 0xbe, 0x90, 0x22, 0x6f, 0x76, 0x90, 0x76, 0x83, 0x87,
    0x99, 0xdb, 0x59, 0xe0, 0x76, 0x80, 0x16, 0x3b, 0xc3, 0x03, 0x8c, 0x6e, 0x80, 0x00, 0x00, 0x01,
    0x02, 0x5f, 0xed, 0xdf, 0x1a, 0xd3, 0x45, 0x0e, 0x4d, 0x12,
];

fn context(suite: SrtpCryptoSuite) -> SrtpContext {
    SrtpContext::new(
        suite,
        SrtpCryptoKey::new(MASTER_KEY.to_vec(), MASTER_SALT.to_vec()),
    )
    .expect("libSRTP vector key must create a context")
}

fn aes256_context(suite: SrtpCryptoSuite) -> SrtpContext {
    SrtpContext::new(
        suite,
        SrtpCryptoKey::new(MASTER_KEY_256.to_vec(), MASTER_SALT.to_vec()),
    )
    .expect("libSRTP AES-256 vector key must create a context")
}

#[test]
fn protects_rtp_to_libsrtp_known_answer() {
    let packet = RtpPacket::parse(&RTP_PLAINTEXT).expect("valid RTP vector");
    let wire = context(SRTP_AES128_CM_SHA1_80)
        .protect(&packet)
        .expect("protect RTP vector")
        .serialize()
        .expect("serialize protected RTP vector");
    assert_eq!(wire.as_ref(), SRTP_CIPHERTEXT);
}

#[test]
fn unprotects_libsrtp_srtp_known_answer() {
    let packet = context(SRTP_AES128_CM_SHA1_80)
        .unprotect(&SRTP_CIPHERTEXT)
        .expect("unprotect libSRTP vector");
    assert_eq!(packet.serialize().unwrap().as_ref(), RTP_PLAINTEXT);
}

#[test]
fn protects_rtcp_to_libsrtp_known_answer() {
    let wire = context(SRTP_AES128_CM_SHA1_80)
        .protect_rtcp(&RTCP_PLAINTEXT)
        .expect("protect RTCP vector");
    assert_eq!(wire.as_ref(), SRTCP_CIPHERTEXT);
}

#[test]
fn unprotects_libsrtp_srtcp_known_answer() {
    let packet = context(SRTP_AES128_CM_SHA1_80)
        .unprotect_rtcp(&SRTCP_CIPHERTEXT)
        .expect("unprotect libSRTP SRTCP vector");
    assert_eq!(packet.as_ref(), RTCP_PLAINTEXT);
}

#[test]
fn sha1_32_protects_rtp_to_libsrtp_known_answer() {
    let packet = RtpPacket::parse(&RTP_PLAINTEXT).expect("valid RTP vector");
    let wire = context(SRTP_AES128_CM_SHA1_32)
        .protect(&packet)
        .expect("protect SHA1-32 RTP vector")
        .serialize()
        .expect("serialize protected SHA1-32 RTP vector");
    assert_eq!(wire.as_ref(), SRTP_SHA1_32_CIPHERTEXT);
}

#[test]
fn sha1_32_unprotects_libsrtp_srtp_known_answer() {
    let packet = context(SRTP_AES128_CM_SHA1_32)
        .unprotect(&SRTP_SHA1_32_CIPHERTEXT)
        .expect("unprotect libSRTP SHA1-32 vector");
    assert_eq!(packet.serialize().unwrap().as_ref(), RTP_PLAINTEXT);
}

#[test]
fn sha1_32_protects_srtcp_with_the_libsrtp_80_bit_tag() {
    let wire = context(SRTP_AES128_CM_SHA1_32)
        .protect_rtcp(&RTCP_PLAINTEXT)
        .expect("protect SHA1-32 RTCP vector");
    assert_eq!(wire.as_ref(), SRTCP_CIPHERTEXT);
}

#[test]
fn sha1_32_unprotects_libsrtp_srtcp_known_answer() {
    let packet = context(SRTP_AES128_CM_SHA1_32)
        .unprotect_rtcp(&SRTCP_CIPHERTEXT)
        .expect("unprotect libSRTP SHA1-32 SRTCP vector");
    assert_eq!(packet.as_ref(), RTCP_PLAINTEXT);
}

#[test]
fn aes256_profiles_match_pinned_libsrtp_rtp_answers_bidirectionally() {
    for (suite, expected) in [
        (SRTP_AES256_CM_SHA1_80, &SRTP_AES256_SHA1_80_CIPHERTEXT[..]),
        (SRTP_AES256_CM_SHA1_32, &SRTP_AES256_SHA1_32_CIPHERTEXT[..]),
    ] {
        let packet = RtpPacket::parse(&RTP_PLAINTEXT).unwrap();
        let wire = aes256_context(suite.clone())
            .protect(&packet)
            .unwrap()
            .serialize()
            .unwrap();
        assert_eq!(wire.as_ref(), expected);
        assert_eq!(
            aes256_context(suite)
                .unprotect(expected)
                .unwrap()
                .serialize()
                .unwrap()
                .as_ref(),
            RTP_PLAINTEXT
        );
    }
}

#[test]
fn aes256_profiles_match_pinned_libsrtp_srtcp_answer_bidirectionally() {
    for suite in [SRTP_AES256_CM_SHA1_80, SRTP_AES256_CM_SHA1_32] {
        let wire = aes256_context(suite.clone())
            .protect_rtcp(&RTCP_PLAINTEXT)
            .unwrap();
        assert_eq!(wire.as_ref(), SRTCP_AES256_CIPHERTEXT);
        assert_eq!(
            aes256_context(suite)
                .unprotect_rtcp(&SRTCP_AES256_CIPHERTEXT)
                .unwrap()
                .as_ref(),
            RTCP_PLAINTEXT
        );
    }
}
